version: "3"
services:
  db:
    image: postgres:16.1
    command:
      ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
      POSTGRES_LOGGING: all
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./database
        target: /docker-entrypoint-initdb.d
    logging:
      options:
        max-size: "10k"
        max-file: "5"
    profiles:
      - app

  frontend:
    build: frontend
    ports:
      - "3000:3000"
    command: bash -c "pnpm install && pnpm dev"
    volumes:
      - type: bind
        source: ./frontend/
        target: /frontend/
    profiles:
      - app
      - frontend-mock

  backend:
    build: backend
    ports:
      - "8080:8080"
    command: bash -c " /scripts/wait-for-it.sh db:5432 --timeout=60 --strict && air"
    volumes:
      - type: bind
        source: ./backend
        target: /backend
      - type: bind
        source: ./openapi
        target: /openapi
      - type: bind
        source: ./design_files
        target: /design_files
    depends_on:
      - db
    profiles:
      - app

  nginx:
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
      - swagger-ui
    profiles:
      - app

  nginx-frontend:
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/default-mock.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - prism
      - frontend
      - swagger-ui
    profiles:
      - frontend-mock

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "4000:8080"
    volumes:
      - ./design_files/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
      BASE_URL: /swagger
    profiles:
      - app
      - frontend-mock

  prism:
    image: stoplight/prism:4
    command: "mock -h 0.0.0.0 /openapi.yaml"
    volumes:
      - ./design_files/openapi.yaml:/openapi.yaml
    ports:
      - "8080:4010"
    profiles:
      - frontend-mock

  openapi-generator:
    image: openapitools/openapi-generator-cli
    volumes:
      - ./design_files/openapi.yaml:/design_files/openapi.yaml
      - ./frontend/:/frontend/
    profiles:
      - tools
